In [2]:
import numpy as np
from scipy.linalg import svd

#### Problem 1


Explanation: To determine the number of linearly independent columns (i.e. the rank) of a matrix A, we can apply a numerical SVD factorization method to the matrix. 
The number of non-zero values in the sigma (singular values) matrix will represent the rank of the matrix A.

In [3]:
#### Code

A = np.array([
    [-1.32, -0.18, 2.13], 
    [2.64,  -4.68, 4.65], 
    [1.47,  -4.75, 6.80]
])

_, S, _ = svd(A)
rank = np.count_nonzero(np.round(S, decimals=4))
print("number of LI columns in A (i.e. its rank): ", rank)


number of LI columns in A (i.e. its rank):  2


#### Problem 2

In [4]:
#TO_DO: handwritten explanation

Python Explanation:
We can reproduce the handwritten approach programmatically to determine the parameters for the best fit linear estimate using least squares estimation:

In [5]:
x = np.array([-1.0, 2.5, 6.0, -3.5, 3.0, 8.5])
B = np.array([8.5, 3.0, -5.5, 13.0, 0.0, -10.0])
A = np.zeros((x.size, 2))
for i, elem in enumerate(x):
    A[i] = np.array([elem, 1])

A_T = np.transpose(A)

## note: component C1: (A_transpose * A) ends up having a non-zero determinant, proving it is invertible
## this number also matches our handwritten expression above
C1 = np.dot(A_T, A)
# print(round(np.linalg.det(C1)), "\n")

C1_INV = np.linalg.inv(C1)
C2 = np.dot(A_T, B)

## SOLUTION: this is the parameter q we are solving for in Aq = p_hat 
# (where p_hat is our closest vector estimate that still falls in A's columnspace)
LEAST_SQ_EST_PARAMS = np.round(np.dot(C1_INV, C2), 2)
print(LEAST_SQ_EST_PARAMS)

[-1.94  6.52]


#### Problem 3

Yes, `w_1`, `w_2` and `w_3` would be a valid set of basis vectors for `R_3`. There are two considerations here:
1. Dimensional consistency: Each vector is made of up three components, one for each dimension of R_3
2. Linear Independence: If you concatenate the three vectors together, you can quickly see that they are linear independent because they form a 3x3 matrix in upper triangular form. 

Note: The bottom components of `w_1` and `w_2` are both 0, indicating that there would be no possible linear combination of those two vectors that would yield the required "k_hat" component (`1`) in the `w_3` vector.

#### Problem 4

Similarly (to problem 3), `t_1`, `t_2` and `t_3` form a valid set of basis vectors for `R_3`. Once again, concatenating these three vectors forms an upper triangular matrix (and therefore one with linear independent column vectors). Additionally, note that this combination of vectors represents a rotation matrix about the "z" axis, which would mean that the transformation does not reduce the dimensionality of the output vectorspace (i.e. this matrix would be invertible, which can be further proven by showing the determinant of the matrix to be non-zero. It will be 1 which represents a pure retention of the area of columnspace represented by A).

In [6]:
A = np.array([
    [0.707,   0.707,  0], 
    [-0.707,  0.707,  0], 
    [0,       0,      1]
])

print("det(A): ", round(np.linalg.det(A)))

det(A):  1


#### Problem 5

The vectors `w_1` through `w_4` do span `R_3` since they each have 3 components, one for each dimension of `R_3`. However, they are not all linearly independent and therefore would not form a basis for `R_3`. Note that `w_1` through `w_3` by themselves would form an upper triangular matrix and would therefore be easily identified as being linearly independent, similar to Problems 3 and 4. `w_4` can be derived as a linear combination of `2(w_1) - w_2 + 3(w_3)` and is therefore redundant. The arithmetic would look like:

```python
# [
#     2(1) -1(1) + 3(0) = 1,
#     2(0) -1(1) + 3(1) = 2,
#     2(0) -1(0) + 3(1) = 3
# ]
```


#### Problem 6

In [86]:
# APPROACH: I'm using exclusively randomly generated values to show that SVD can always be used to determine rank
# (even for linear combinations of floats)

# we generate a third vector v3 by performing a random linear combination of v1 and v2
coeffs = (np.random.randint(10), round(np.random.randint(10)))
v1 = np.random.randint(-10, 10, size=3)
v2 = np.random.randint(-10, 10, size=3)
v3 = np.array([(coeffs[0]*a - coeffs[1]*b) for a, b in zip(v1, v2)])
print("component vectors v1, v2, v3: \n", v1, "\n",  v2, "\n",  v3, "\n")

A = np.stack((v1, v2, v3), axis=1)
print("target matrix A: \n", A, "\n")

# we then perform SVD on the overall matrix, and filter out any almost-zero singular values
# counting the rest of the singular values yields the rank of the original matrix M
U, S, VT = svd(A)
rank = np.count_nonzero(np.round(S, decimals=4))
print("number of LI columns in A (i.e. its rank): ", rank)

# general nullspace intuition: for matrices that are not full rank (output vectorspace is reduced to a lower dimension),
# there is a set of input vectors that will end up being transformed to the 0 vector. This set is called the nullspace. 

# note: the last n - r columns in VT form a set of orthonormal basis vectors of the matrix A's nullspace
zero_sv_column_indices = (S < 0.0001).nonzero()[0]
nullspace_basis = VT[:,zero_sv_column_indices]
print("an orthonormal set of basis vectors for the nullspace of A: \n", nullspace_basis)


component vectors v1, v2, v3: 
 [-5  5 -9] 
 [-3 -3  8] 
 [  3  33 -75] 

target matrix A: 
 [[ -5  -3   3]
 [  5  -3  33]
 [ -9   8 -75]] 

number of LI columns in A (i.e. its rank):  2
an orthonormal set of basis vectors for the nullspace of A: 
 [[ 0.98715605]
 [-0.06151261]
 [ 0.14744196]]
